Repository whilp/world, pull requests merged in 2020-12, with the labels that each got.

#594 devcontainer: switch to gitlens insiders
  .devcontainer.json
Labels: feat

#613 renovate: group rules_nodejs updates
  renovate.js
Labels: feat

#618 cmd/bot: pin (old) docker image
  cmd/bot/action.yml
Labels: fix

#620 bump rules_pkg to 0.3.0
  WORKSPACE
Labels: dependencies

#623 renovate: rebase when behind base branch
  renovate.js
Labels: fix

#395 fix: ensure go build cache is writable
  .github/workflows/update.yml
Labels: fix

#458 versions: fix path to input
  versions/BUILD.bazel
  versions/versions.bzl
Labels: fix

#460 cmd: add pyright
  .github/matchers.json
  .github/workflows/lint.yml
  .github/workflows/push.yml
  BUILD.bazel
  cmd/bandit/bandit.py
  cmd/black/black.py
  cmd/pyright/BUILD.bazel
  cmd/pyright/test.json
  package.json
  pyrightconfig.json
  requirements/__init__.py
  requirements/compile.py
  requirements/test.py
  yarn.lock
Labels: feat

#630 simplify bot configuration
  cmd/bot/BUILD.bazel
  cmd/bot/action.yml
  cmd/bot/index.ts
Labels: feat

#634 cmd: add shellcheck
  .github/matchers.json
  .github/workflows/lint.yml
  cmd/shellcheck/BUILD.bazel
  cmd/shellcheck/shellcheck.go
  cmd/shellcheck/test.json
Labels: feat

#636 cmd/gazelle: configure linter
  .github/workflows/lint.yml
  cmd/gazelle/BUILD.bazel
  cmd/gazelle/test.json
  cmd/tools/main.go
  image/devcontainer/BUILD.bazel
  image/devcontainer/test.json
Labels: feat

#639 lint: detect untracked files
  .github/workflows/lint.yml
Labels: fix

#641 README: add action status badges
  README.md
Labels: feat

#642 github: don't check label on PR open
  .github/workflows/github.yml
Labels: fix

#644 Fix a BUNCH of little glitches in my bad bot auth changes
  cmd/bot/BUILD.bazel
  cmd/bot/action.yml
  cmd/bot/index.ts
  package.json
  yarn.lock
Labels: fix
